CREATE TABLE [IF NOT EXISTS] workout (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
)

CREATE TABLE [IF NOT EXISTS] exercise (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    CONSTRAINT fk_workout FOREIGN KEY(fk_workout) REFERENCES workout(id)
)
