// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Exercise struct {
	ID        int64
	Name      string
	WorkoutID int32
}

type Workout struct {
	ID   int64
	Name string
}
