// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID        int64
	Name      string
	WorkoutID pgtype.Int4
}

type Workout struct {
	ID   int64
	Name string
}
